apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2023-08-12T19:26:11.000Z
  labels:
    app: rate-limiter-app
  name: rate-limiter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limiter-app
  template:
    metadata:
      labels:
        app: rate-limiter-app
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: rate-limiter-app
        tty: true
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #imagePullSecrets:
        #- name: dockerhub
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: rate-limiter-db-password
              key: password
