apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rate-limiter-db-password-es
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: rate-limiter-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: rate-limiter-db-password
