#The workflow assumes that the required GCP secrets (GCP_PROJECT_ID, GCP_WORKLOAD_IDENTITY_PROVIDER, GCP_SERVICE_ACCOUNT_EMAIL) are set in the repository.
#The region (us-central1) and repository (lab) are hardcoded for clarity but can be parameterized further if needed.
# provision GAR

# This workflow builds and pushes a Docker image to Docker Hub using official actions.
# It uses secrets for Docker Hub credentials and repository, ensuring no sensitive data is hardcoded.
# The image is tagged with the commit SHA for traceability.
# The workflow is modular and environment-agnostic, following CI/CD best practices.

name: CI - Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: rate-limiter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: homelab
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using official action
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image using official Docker action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

